### ISSUE TITLE
Option to specify installation ID instead of installing app into calling repo

### ISSUE THREAD

**Issue by thormick** [peter-murray/workflow-application-token-action#11]
The npm script [github-app-installation-token](https://github.com/gagoar/github-app-installation-token) ([NPMJS](https://www.npmjs.com/package/github-app-installation-token)), takes a installation ID for the target repo with the workflow that is to be triggered, so the GitHub Application only has to be installed in the repo that has the workflow that is to be triggered. Could workflow-application-token-action be enhanced with this feature, so one doesn't also have to install the app into the repo that triggers the workflow?

I managed to get everything working when I tested it from the command line with that script, so it was a little bit of a d'oh when I setup another repo with a workflow that ran workflow-application-token-action and that failed.

**Comment by peter-murray** [comment]
The `installation id` of the application is looked up utilizing the repository or organization name. I prefer to utilize this method as installation ids are extremely difficult to work out where they are inside an enterprise/organization/repository.

Also the need to install the application is required so that you can gain the permissions the application is requesting, so it 
has to be installed somewhere. 

Whilst I could support the injection of the `installation id` directory from the caller it does create more opportunities for errors from users, difficult to report errors, and makes it difficult to trace what actual application installation is being referenced in the workflows.

Can you provide some more context as to the full use case here, as this supports both organization and repository level installations (and both have the lookup functionality of the `installation id`) and any supporting context will help.

**Comment by jrarmstro** [comment]
I would like to generate a credential which has access to a particular list of repositories - not the entire org. However, the entire org should be able to use this credential (so that all repos can access the specified repositories).

As it stands, this does not seem to be possible?
