### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by dudicoco** [peter-murray/workflow-application-token-action#35]
It seems that no new releases were created for the action for a few months now even though there have been code changes.

Please create releases when changes have been made so users can be notified.

**Comment by peter-murray** [comment]
The latest commit that was not tag was just an update the to the README to bump the version in the examples to v2.

The last release was v2.1.0 and that is present in the releases. What is it that is not showing for you?

**Comment by dudicoco** [comment]
Thanks, I didn't check the commit history before opening this.
So perhaps the issue here is that there need to be more updates to the project to keep it well maintained, did you consider adding dependabot or renovate for automatic updates of dependencies?

**Comment by peter-murray** [comment]
Thanks, I do use dependabot on the project. The last two commits as stated since the last release were docs changes, nothing that required a release version number change.

The project is pretty lightweight, I dislike too many dependencies unless they serve a purpose, this is why it is easy to maintain.
